"""Declarative finite-CSP project built on Snarky choices."""

from .constraint_syntax import (
    PersistentConstraintKind,
    PersistentConstraintTemplate,
    instantiate_constraint_templates,
    parse_constraint_templates,
)
from .persistent_constraints import (
    AllDifferentConstraint,
    BinaryComparisonConstraint,
    BinaryComparisonOperator,
    CandidateRemovalExplanation,
    ConstraintOperator,
    CountConstraint,
    ElementConstraint,
    GlobalCardinalityConstraint,
    LexLessEqualConstraint,
    LinearSumConstraint,
    PersistentConstraint,
    PersistentConstraintPropagator,
    SumConstraint,
    TableConstraint,
)
from .solver import (
    BinaryCSP,
    FiniteCSP,
    FiniteCSPRuleLibrary,
    assignment_from_solution,
    binary_constraint_facts,
    constraint_dom_wdeg_policy,
    constraint_learned_impact_policy,
    constraint_propagation_guided_policy,
    finite_csp_rule_library,
    solve_binary_csp,
    solve_finite_csp,
)

__all__ = [
    "AllDifferentConstraint",
    "BinaryCSP",
    "BinaryComparisonConstraint",
    "BinaryComparisonOperator",
    "CandidateRemovalExplanation",
    "ConstraintOperator",
    "CountConstraint",
    "ElementConstraint",
    "FiniteCSP",
    "FiniteCSPRuleLibrary",
    "GlobalCardinalityConstraint",
    "LexLessEqualConstraint",
    "LinearSumConstraint",
    "PersistentConstraint",
    "PersistentConstraintKind",
    "PersistentConstraintPropagator",
    "PersistentConstraintTemplate",
    "SumConstraint",
    "TableConstraint",
    "assignment_from_solution",
    "binary_constraint_facts",
    "constraint_dom_wdeg_policy",
    "constraint_learned_impact_policy",
    "constraint_propagation_guided_policy",
    "finite_csp_rule_library",
    "instantiate_constraint_templates",
    "parse_constraint_templates",
    "solve_binary_csp",
    "solve_finite_csp",
]
