"""Public API of the Snarky inference engine."""

from .actions import Action, AddFact, Let, RemoveFact, add, let, remove
from .engine import (
    EngineLimits,
    FactExists,
    FactMutationKind,
    ForwardEngine,
    GroupExecutionMode,
    GroupRunResult,
    GroupStopReason,
    InferenceEvent,
    InferenceLimitError,
    InferenceSession,
    RunResult,
    StopCondition,
)
from .expressions import (
    ArithmeticEvaluationError,
    BinaryArithmeticExpression,
    BinaryArithmeticOperator,
    NumericExpression,
    UnaryArithmeticExpression,
    UnaryArithmeticOperator,
    evaluate_arithmetic,
)
from .facts import Fact
from .instantiation import (
    FactDelta,
    IndexedInstantiationStrategy,
    InstantiationMetrics,
    InstantiationStrategy,
    NaiveInstantiationStrategy,
    SemiNaiveInstantiationStrategy,
)
from .matching import PatternMatcher
from .parser import (
    ParseError,
    parse_arithmetic_expression,
    parse_rule_groups,
    parse_rules,
    parse_term,
)
from .plans import TechniquePlan, TechniquePlanResult, TechniquePlanStatus
from .premises import (
    ComparisonOperator,
    ComparisonPremise,
    CountPremise,
    ExistsPremise,
    FactPremise,
    NotExistsPremise,
    UniquePremise,
    count,
    exists,
    not_exists,
    unique,
)
from .rules import Rule, RuleGroup, when
from .substitutions import EMPTY_SUBSTITUTION, Substitution
from .terms import (
    Atom,
    Number,
    Proposition,
    Status,
    Term,
    Triple,
    Variable,
    is_ground,
    render_term,
    variables_in,
)
from .unification import Unifier

__all__ = [
    "EMPTY_SUBSTITUTION",
    "Action",
    "AddFact",
    "ArithmeticEvaluationError",
    "Atom",
    "BinaryArithmeticExpression",
    "BinaryArithmeticOperator",
    "ComparisonOperator",
    "ComparisonPremise",
    "CountPremise",
    "EngineLimits",
    "Fact",
    "FactDelta",
    "FactExists",
    "FactMutationKind",
    "FactPremise",
    "ExistsPremise",
    "ForwardEngine",
    "GroupExecutionMode",
    "GroupRunResult",
    "GroupStopReason",
    "InferenceLimitError",
    "InferenceEvent",
    "InferenceSession",
    "IndexedInstantiationStrategy",
    "InstantiationMetrics",
    "InstantiationStrategy",
    "Let",
    "Number",
    "NotExistsPremise",
    "NaiveInstantiationStrategy",
    "NumericExpression",
    "ParseError",
    "PatternMatcher",
    "Proposition",
    "Rule",
    "RuleGroup",
    "RemoveFact",
    "RunResult",
    "SemiNaiveInstantiationStrategy",
    "Status",
    "StopCondition",
    "Substitution",
    "Term",
    "TechniquePlan",
    "TechniquePlanResult",
    "TechniquePlanStatus",
    "Triple",
    "UnaryArithmeticExpression",
    "UnaryArithmeticOperator",
    "Unifier",
    "UniquePremise",
    "Variable",
    "add",
    "count",
    "evaluate_arithmetic",
    "exists",
    "is_ground",
    "let",
    "not_exists",
    "parse_arithmetic_expression",
    "parse_rule_groups",
    "parse_rules",
    "parse_term",
    "remove",
    "unique",
    "render_term",
    "variables_in",
    "when",
]
